---
--- Generated by Luanalysis
--- Created by etix-2021-05.
--- DateTime: 2021/6/28 10:53
---
-- 文档地址：https://www.tutorialspoint.com/lua/lua_decision_making.htm
-- if
a = 10
b = 15
if (a > 0) then
    print("value of a:", a)
end
if (a > b) then
    print("a > b")
else
    print("a < b")
end
